/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.politecnica.federico.hdfswritertest1;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class AttackPropertyValue extends org.apache.thrift.TUnion<AttackPropertyValue, AttackPropertyValue._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AttackPropertyValue");
  private static final org.apache.thrift.protocol.TField SUMMARY_FIELD_DESC = new org.apache.thrift.protocol.TField("summary", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField LATITUDE_FIELD_DESC = new org.apache.thrift.protocol.TField("latitude", org.apache.thrift.protocol.TType.DOUBLE, (short)2);
  private static final org.apache.thrift.protocol.TField LONGITUDE_FIELD_DESC = new org.apache.thrift.protocol.TField("longitude", org.apache.thrift.protocol.TType.DOUBLE, (short)3);
  private static final org.apache.thrift.protocol.TField NKILLS_FIELD_DESC = new org.apache.thrift.protocol.TField("nkills", org.apache.thrift.protocol.TType.I64, (short)4);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SUMMARY((short)1, "summary"),
    LATITUDE((short)2, "latitude"),
    LONGITUDE((short)3, "longitude"),
    NKILLS((short)4, "nkills");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SUMMARY
          return SUMMARY;
        case 2: // LATITUDE
          return LATITUDE;
        case 3: // LONGITUDE
          return LONGITUDE;
        case 4: // NKILLS
          return NKILLS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SUMMARY, new org.apache.thrift.meta_data.FieldMetaData("summary", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LATITUDE, new org.apache.thrift.meta_data.FieldMetaData("latitude", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.LONGITUDE, new org.apache.thrift.meta_data.FieldMetaData("longitude", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.NKILLS, new org.apache.thrift.meta_data.FieldMetaData("nkills", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AttackPropertyValue.class, metaDataMap);
  }

  public AttackPropertyValue() {
    super();
  }

  public AttackPropertyValue(_Fields setField, java.lang.Object value) {
    super(setField, value);
  }

  public AttackPropertyValue(AttackPropertyValue other) {
    super(other);
  }
  public AttackPropertyValue deepCopy() {
    return new AttackPropertyValue(this);
  }

  public static AttackPropertyValue summary(java.lang.String value) {
    AttackPropertyValue x = new AttackPropertyValue();
    x.setSummary(value);
    return x;
  }

  public static AttackPropertyValue latitude(double value) {
    AttackPropertyValue x = new AttackPropertyValue();
    x.setLatitude(value);
    return x;
  }

  public static AttackPropertyValue longitude(double value) {
    AttackPropertyValue x = new AttackPropertyValue();
    x.setLongitude(value);
    return x;
  }

  public static AttackPropertyValue nkills(long value) {
    AttackPropertyValue x = new AttackPropertyValue();
    x.setNkills(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, java.lang.Object value) throws java.lang.ClassCastException {
    switch (setField) {
      case SUMMARY:
        if (value instanceof java.lang.String) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type java.lang.String for field 'summary', but got " + value.getClass().getSimpleName());
      case LATITUDE:
        if (value instanceof java.lang.Double) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type java.lang.Double for field 'latitude', but got " + value.getClass().getSimpleName());
      case LONGITUDE:
        if (value instanceof java.lang.Double) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type java.lang.Double for field 'longitude', but got " + value.getClass().getSimpleName());
      case NKILLS:
        if (value instanceof java.lang.Long) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type java.lang.Long for field 'nkills', but got " + value.getClass().getSimpleName());
      default:
        throw new java.lang.IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected java.lang.Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case SUMMARY:
          if (field.type == SUMMARY_FIELD_DESC.type) {
            java.lang.String summary;
            summary = iprot.readString();
            return summary;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case LATITUDE:
          if (field.type == LATITUDE_FIELD_DESC.type) {
            java.lang.Double latitude;
            latitude = iprot.readDouble();
            return latitude;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case LONGITUDE:
          if (field.type == LONGITUDE_FIELD_DESC.type) {
            java.lang.Double longitude;
            longitude = iprot.readDouble();
            return longitude;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case NKILLS:
          if (field.type == NKILLS_FIELD_DESC.type) {
            java.lang.Long nkills;
            nkills = iprot.readI64();
            return nkills;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new java.lang.IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case SUMMARY:
        java.lang.String summary = (java.lang.String)value_;
        oprot.writeString(summary);
        return;
      case LATITUDE:
        java.lang.Double latitude = (java.lang.Double)value_;
        oprot.writeDouble(latitude);
        return;
      case LONGITUDE:
        java.lang.Double longitude = (java.lang.Double)value_;
        oprot.writeDouble(longitude);
        return;
      case NKILLS:
        java.lang.Long nkills = (java.lang.Long)value_;
        oprot.writeI64(nkills);
        return;
      default:
        throw new java.lang.IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected java.lang.Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case SUMMARY:
          java.lang.String summary;
          summary = iprot.readString();
          return summary;
        case LATITUDE:
          java.lang.Double latitude;
          latitude = iprot.readDouble();
          return latitude;
        case LONGITUDE:
          java.lang.Double longitude;
          longitude = iprot.readDouble();
          return longitude;
        case NKILLS:
          java.lang.Long nkills;
          nkills = iprot.readI64();
          return nkills;
        default:
          throw new java.lang.IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new org.apache.thrift.protocol.TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case SUMMARY:
        java.lang.String summary = (java.lang.String)value_;
        oprot.writeString(summary);
        return;
      case LATITUDE:
        java.lang.Double latitude = (java.lang.Double)value_;
        oprot.writeDouble(latitude);
        return;
      case LONGITUDE:
        java.lang.Double longitude = (java.lang.Double)value_;
        oprot.writeDouble(longitude);
        return;
      case NKILLS:
        java.lang.Long nkills = (java.lang.Long)value_;
        oprot.writeI64(nkills);
        return;
      default:
        throw new java.lang.IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case SUMMARY:
        return SUMMARY_FIELD_DESC;
      case LATITUDE:
        return LATITUDE_FIELD_DESC;
      case LONGITUDE:
        return LONGITUDE_FIELD_DESC;
      case NKILLS:
        return NKILLS_FIELD_DESC;
      default:
        throw new java.lang.IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public java.lang.String getSummary() {
    if (getSetField() == _Fields.SUMMARY) {
      return (java.lang.String)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'summary' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setSummary(java.lang.String value) {
    if (value == null) throw new java.lang.NullPointerException();
    setField_ = _Fields.SUMMARY;
    value_ = value;
  }

  public double getLatitude() {
    if (getSetField() == _Fields.LATITUDE) {
      return (java.lang.Double)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'latitude' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setLatitude(double value) {
    setField_ = _Fields.LATITUDE;
    value_ = value;
  }

  public double getLongitude() {
    if (getSetField() == _Fields.LONGITUDE) {
      return (java.lang.Double)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'longitude' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setLongitude(double value) {
    setField_ = _Fields.LONGITUDE;
    value_ = value;
  }

  public long getNkills() {
    if (getSetField() == _Fields.NKILLS) {
      return (java.lang.Long)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'nkills' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setNkills(long value) {
    setField_ = _Fields.NKILLS;
    value_ = value;
  }

  public boolean isSetSummary() {
    return setField_ == _Fields.SUMMARY;
  }


  public boolean isSetLatitude() {
    return setField_ == _Fields.LATITUDE;
  }


  public boolean isSetLongitude() {
    return setField_ == _Fields.LONGITUDE;
  }


  public boolean isSetNkills() {
    return setField_ == _Fields.NKILLS;
  }


  public boolean equals(java.lang.Object other) {
    if (other instanceof AttackPropertyValue) {
      return equals((AttackPropertyValue)other);
    } else {
      return false;
    }
  }

  public boolean equals(AttackPropertyValue other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(AttackPropertyValue other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  @Override
  public int hashCode() {
    java.util.List<java.lang.Object> list = new java.util.ArrayList<java.lang.Object>();
    list.add(this.getClass().getName());
    org.apache.thrift.TFieldIdEnum setField = getSetField();
    if (setField != null) {
      list.add(setField.getThriftFieldId());
      java.lang.Object value = getFieldValue();
      if (value instanceof org.apache.thrift.TEnum) {
        list.add(((org.apache.thrift.TEnum)getFieldValue()).getValue());
      } else {
        list.add(value);
      }
    }
    return list.hashCode();
  }
  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
